---

- name: Install prerequisites packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - postfix
    - apt-transport-https

- name: Install GitLab GPG key
  apt_key:
    state: present
    url: "{{ gitlab_gpg_key }}"

- name: Add sources list
  apt_repository:
    repo: "{{ gitlab_repository }}"
    state: present

- name: Install GitLab CE
  apt:
    name: "gitlab-ce={{ gitlab_version }}{{ gitlab_version_suffix }}"
    state: present
    update_cache: yes
  notify:
    - reconfigure gitlab
    - restart gitlab
    - wait for unicorn
    - start postfix

- name: Configure Gitlab
  template:
    src: "etc/gitlab/gitlab.rb.j2"
    dest: "/etc/gitlab/gitlab.rb"
    owner: root
    group: root
    mode: 0600
  notify:
    - reconfigure gitlab
    - restart gitlab
  tags:
    - config
