---

- name: GITLAB | Manage Debian environment
  import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: GITLAB | Manage RedHat environment
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: GITLAB | Configure Gitlab
  template:
    src: "etc/gitlab/gitlab.rb.j2"
    dest: "/etc/gitlab/gitlab.rb"
    owner: root
    group: root
    mode: 0600
  notify:
    - reconfigure gitlab
    - restart gitlab
